
# mysql setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cucumber
    username:
    password:
    maximum-pool-size: 20
mybatis:
  mapper-locations: classpath:/sqlmapper/mappers/**/*.xml
