
# mysql setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cucumber
    username:
    password:
    maximum-pool-size: 20

mybatis:
  mapper-locations: classpath:/sqlmapper/mappers/**/*.xml

# Google
google:
  client:
    id:
    pw:
    scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
    callback-url: http://localhost:8080/user/singin/callback/google
    auth-url: https://accounts.google.com/o/oauth2/v2/auth
    token-request-url: https://oauth2.googleapis.com/token
    useinfo-request-url: https://www.googleapis.com/oauth2/v1/userinfo
