
# mysql setting
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/cucumber?autoReconnect=true&useSSL=false&allowMultiQueries=true
      username:
      password:
      maximum-pool-size: 20

