
# mysql setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${{secrets.SPRING_DATASOURCE_URL}}
    username: ${{secrets.SPRING_DATASOURCE_USERNAME}}
    password: ${{secrets.SPRING_DATASOURCE_PASSWORD}}
    maximum-pool-size: 20
mybatis:
  #  check-config-location: true
  mapper-locations: classpath:/sqlmapper/mappers/**/*.xml
  config-location: classpath:/sqlmapper/sql-mapper-config.xml

# log4jdbc, Mybatis Console Log
logging:
  level:
    com:
      zaxxer:
        hikari: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: DEBUG  #SQL 결과 데이터 Table을 로그로 남긴다.
      sqlonly: OFF     #SQL만 로그로 남긴다.
      sqltiming: INFO    #SQL과 소요시간을 표기한다.
      connection : OFF  # 커넥션 확인가능

# Google
google:
  client:
    id: ${{secrets.GOOGLE_CLIENT_ID}}
    pw: ${{secrets.GOOGLE_CLIENT_PW}}
    scope: ${{secrets.GOOGLE_CLIENT_SCOPE}}
    callback-url: ${{secrets.GOOGLE_CLIENT_CALLBACK_URL}}
    auth-url: ${{secrets.GOOGLE_CLIENT_AUTH_URL}}
    token-request-url: ${{secrets.GOOGLE_CLIENT_TOKEN_REQUEST_URL}}
    userinfo-request-url: ${{secrets.GOOGLE_CLIENT_USERINFO_REQUEST_URL}}