name: Java CI with Gradle

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set application.yml
      uses: microsoft/variable-substitution@v1 
      with:
        files: ./src/main/resources/application.yml 
      env:
        spring.datasource.url: ${{ secrets.SPRING_DATASOURCE_URL }} 
        spring.datasource.username: ${{ secrets.SPRING_DATASOURCE_USERNAME }} 
        spring.datasource.password: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
        
        google.client.id: ${{ secrets.GOOGLE_CLIENT_ID }}
        google.client.pw: ${{ secrets.GOOGLE_CLIENT_PW }}
        google.client.scope: ${{ secrets.GOOGLE_CLIENT_SCOPE }}
        google.client.callback-url: ${{ secrets.GOOGLE_CLIENT_CALLBACK_URL }}
        google.client.auth-url: ${{ secrets.GOOGLE_CLIENT_AUTH_URL }}
        google.client.token-request-url: ${{ secrets.GOOGLE_CLIENT_TOKEN_REQUEST_URL }}
        google.client.userinfo-request-url: ${{ secrets.GOOGLE_CLIENT_USERINFO_REQUEST_URL }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Make Gradlew Executable
      run: chmod +x ./gradlew

    - name: Cache
      uses: actions/cache@v4.0.2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
